name: page_view_indicator
version: 0.3.1
description: Builds indication marks for PageView.
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/page_view_indicator

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
